// THE STATUS CATALOG — one row per real Raydar system, David's view.
//
// Spec: docs/PRD-STATUS-TAB-2026-08-21.md §4.1 (main repo davidmetawork/raydar),
// reshaped 2026-08-22 per David's iteration feedback: importance-first strips
// with drawn flow diagrams, not four equal card groups.
// Derived 2026-08-21 from the union of the Emails lane inventory (lanes.mjs),
// the Health check catalog, 17 GitHub Actions workflows, the launchd
// inventory, 33 Vercel crons across 6 projects, 3 Fly apps, 12 n8n workflows,
// Paraform-platform sequences, and 8 Claude scheduled tasks — ~120 raw
// entries collapsed to 47 systems. Every alias is recorded in `dupes` so the
// completeness test can prove nothing was dropped.
//
// Field notes:
//   priority     1-5, importance band for the one continuous strip list.
//                1 = the candidate-facing email lanes David watches first
//                (match emails, Para AI outreach, interview invites,
//                sequences); 2 = the rest of the candidate emails; 3 =
//                Paraform writes; 4 = background readers; 5 = infrastructure.
//                Unhealthy rows float to the top WITHIN their band only.
//   state        David's words: sending | paused | not-yet | read-only |
//                manual | frozen. NEVER operator jargon.
//   healthIds    join keys into the Health catalog. Empty => the row MUST
//                carry `gap` ("why there is no signal") and renders hollow,
//                never green.
//   workflow     GitHub Actions run-history join key (one file), or null.
//   feed         clients.raydar.xyz public projection join key, or null.
//   flow         a declarative pipeline diagram the page draws when the row
//                expands: { stages: [{ id, label, countKey?, accent?,
//                secondary?, histogramKey? }], edges: [[from, to]],
//                sourceNote?, countsNote? }. countKey is a dotted path the
//                aggregator resolves against data it ALREADY holds (the two
//                public feeds plus derived convenience numbers) — a missing
//                path renders "—" with a "no data yet" note, NEVER a fake
//                zero. Rows without `flow` get a generic trigger→action
//                sketch drawn from cadence + impact chips; no stage counts
//                are ever invented for them.
//   davidAction  a standing to-do only David can do; `when` is a rule the
//                aggregator evaluates live (see WHEN_RULES) — an item shows
//                only while its signal is live.
//   unverified   facts research could not pin down; rendered with a marker
//                rather than silently guessed.
//   dupes        alias ids from every source (lanes.mjs lane/reader ids,
//                launchd labels, sibling sub-jobs) owned by this row.

export const INVENTORY_DATE = "2026-08-21";
export const HISTORY_START = "2026-08-22"; // the beatlog ring ships this day

// Permanent honesty note (PRD §7): candidate replies to calls@raydar.xyz are
// read by nobody — the mailbox has senders but no inbound reader.
export const CALLS_INBOX_NOTE =
  "calls@raydar.xyz has no inbound reader — candidate replies to booking emails are read by nobody.";

export const FOOTER_NOTES = [
  `Per-run activity history starts ${HISTORY_START}; earlier runs were not recorded per-run anywhere.`,
  "Per-lane Gmail unit numbers are estimates — Google publishes no way to measure them.",
  "Paraform call volume is measured for match-watch only; every other lane is an estimate.",
  CALLS_INBOX_NOTE,
];

// Static reader estimates for the impact band (real metering is impossible).
export const TOP_READERS = [
  { id: "match-watch", label: "Daily new-match emails", note: "heavy thread-search reads on its daily sweep — the cause of its own 429s" },
  { id: "paraai-outreach", label: "Para AI reply rescan", note: "the #2 read cost on david@" },
  { id: "booking-resume-family", label: "Booking resume sync", note: "the historical #1 (~992k units/day before caching)" },
  { id: "fyxer", label: "Fyxer", note: "vendor reader, largely invisible to monitoring" },
];

// Groups survive as the subtle separators inside the one importance-sorted
// list (and as the API's grouping contract); they are no longer four equal
// page sections.
export const GROUPS = [
  { id: "candidate-emails", label: "Candidate emails" },
  { id: "paraform-writes", label: "Paraform writes" },
  { id: "background-readers", label: "Background readers" },
  { id: "infrastructure", label: "Infrastructure" },
];

export const STATES = ["sending", "paused", "not-yet", "read-only", "manual", "frozen"];
export const GMAIL_CLASSES = ["none", "reads", "sends", "both"];
export const PARAFORM_CLASSES = ["none", "reads", "writes", "both"];
export const PRIORITIES = [1, 2, 3, 4, 5];

// davidAction.when rules the aggregator understands.
export const WHEN_RULES = ["tile-paraform-session-down", "health-row-paused", "while-not-yet"];

const HEALTH = "/#health";
const EMAILS = "/#emails";

export const SYSTEMS = [
  // ────────────────────────────────────────────────────────────────────────
  // GROUP 1 — CANDIDATE EMAILS (a candidate or connector can receive these)
  // Priority 1 first — the lanes David named: match emails, Para AI
  // outreach, interview invites, sequences. Then the rest at priority 2.
  // ────────────────────────────────────────────────────────────────────────
  {
    id: "match-watch",
    name: "Daily new-match emails",
    summary: "Every day, candidates we've already talked to are re-checked for new matching roles, and get a personal email when new roles appear.",
    group: "candidate-emails",
    priority: 1,
    state: "sending",
    stateNote: "Armed 2026-08-21; first run sent 32, then Gmail rate-limited it.",
    cadence: "Daily, 4:30am PT sweep; emails land ~7:00am PT.",
    gmail: { class: "both", note: "sends + heavy thread-search reads — its own 429 cause" },
    paraform: { class: "both", note: "~14k reads/run + curated-list adds" },
    healthIds: ["gha-match-watch", "gha-match-watch-deadman"],
    workflow: "match-watch.yml",
    feed: "match-watch-status",
    flow: {
      // ONE CLOCK PER ROW (David's 2026-08-23 ruling): every box in this
      // chain is THIS MORNING's tick, resolved from the latest runsRing
      // entry — the flow never borrows the ledger-wide standing pile (on
      // day one 3,324 examined minus the 3,090-person pile "added up" to
      // 234 by pure coincidence; from day two the two clocks diverge). The
      // standing pile renders as its own labeled strip below the flow, from
      // the feed's `pile` field. People units everywhere: role counts are
      // secondary lines, never a box a person-count box flows into. A feed
      // that predates the per-tick fields (v1) renders "—" for the derived
      // boxes — never a silently mixed clock again.
      stages: [
        { id: "called", label: "Called candidates", countKey: "feed.latestRun.cohort" },
        { id: "examined", label: "Examined this morning", countKey: "feed.latestRun.checked" },
        // checked minus THIS tick's skip total — both from the same ring
        // entry, so the subtraction is real, not cross-clock.
        { id: "matchable", label: "Matchable", countKey: "derived.matchable" },
        {
          id: "adds", label: "People with new roles", countKey: "feed.latestRun.candidatesWithAdds",
          secondary: { label: "roles", countKey: "feed.latestRun.curatedAdds", unit: "roles" },
        },
        // The remainder that makes the people-math visible:
        // examined = matchable + held; matchable = new-roles + nothing-new.
        { id: "nothing", label: "Nothing new today", countKey: "derived.nothingNew" },
        { id: "emailed", label: "Emailed", countKey: "feed.latestRun.sends" },
        {
          id: "owed", label: "Owed an email", countKey: "feed.owed.candidates", accent: "bad-when-positive",
          secondary: { label: "role entries", countKey: "feed.owed.roles", unit: "roles" },
        },
        { id: "held", label: "Held back this morning", histogramKey: "feed.latestRun.skips" },
      ],
      edges: [
        ["called", "examined"], ["examined", "matchable"], ["examined", "held"],
        ["matchable", "adds"], ["matchable", "nothing"],
        ["adds", "emailed"], ["emailed", "owed"],
      ],
      sourceNote: "One clock: every count is this morning's tick, from the lane's own feed (Owed is the standing debt as of that tick). The standing pile below is the all-time view.",
    },
    links: { health: HEALTH, emails: null, registry: "/products/daily-match-watch/" },
    davidAction: null,
    dupes: [],
  },
  {
    id: "paraai-outreach",
    name: "Para AI interview outreach",
    summary: "When a hiring manager requests an interview, the candidate gets a personal email, with follow-ups until they answer.",
    group: "candidate-emails",
    priority: 1,
    state: "sending",
    cadence: "Every 5 minutes (:04 past) on Vercel, plus a resident Fly worker.",
    gmail: { class: "both", note: "sends as david@ (max 3/check); reply-rescan reads are the #2 read cost" },
    paraform: { class: "both", note: "reads requests; resolves them via reply and expired actioning" },
    healthIds: ["email-paraai-outreach", "paraai-lane", "fly-paraai-worker"],
    workflow: null,
    feed: null,
    links: { health: HEALTH, emails: EMAILS, registry: "/products/paraai-outreach/" },
    davidAction: null,
    dupes: ["paraai-first-request", "paraai-additional-request", "paraai-reply-rescan"],
  },
  {
    id: "interview-invites",
    name: "LinkedIn Applicant Email Sequence",
    summary: "Emails LinkedIn applicants inviting them to book an AI interview, then a follow-up after the call.",
    group: "candidate-emails",
    priority: 1,
    state: "sending",
    stateNote: "The desktop job reported exit code 1 on 2026-08-20 — worth a look.",
    cadence: "Hourly at :10 from GitHub Actions (per the lane inventory).",
    unverified: [
      "cadence: lanes.mjs and the migration PRD say hourly :10, the health catalog says 09:10/13:10/17:10 — resolve from the plist",
    ],
    gmail: { class: "sends", note: "1,232 in 8 days; 480/day ceiling" },
    paraform: { class: "reads", note: "role and applicant data" },
    healthIds: ["gha-interview-invites"],
    workflow: "interview-invites.yml",
    feed: "interview-lane-status",
    flow: {
      // Counts resolve from the lane's own published funnel feed
      // (clients.raydar.xyz/interview-lane-status.json — Postgres ledger
      // aggregates plus the plan's pool numbers, counts only). Until the
      // v2 publish lands, the new stages render "—", never zero.
      stages: [
        { id: "applicants", label: "Applicants", countKey: "feed.funnel.applicants" },
        { id: "invited", label: "Invited", countKey: "feed.funnel.enrolled" },
        {
          id: "emailed", label: "Emailed", countKey: "feed.funnel.emailedOnce",
          secondary: { label: "today", countKey: "feed.sentToday" },
        },
        {
          id: "booked", label: "Booked", countKey: "feed.funnel.bookedPeople",
          secondary: { label: "bookings", countKey: "feed.funnel.bookings", unit: "bookings" },
        },
        {
          // David's 2026-08-23 ruling: what actually happened on the call,
          // between Booked and Follow-up sent — the feed's six fixed outcome
          // buckets as small stacked tiles (they sum to total bookings, so
          // the two honesty remainders render too). Amber only where the
          // call itself went wrong; asking for a human is a normal outcome.
          // Per booking, not per person — declared, never implied.
          id: "outcome", label: "What the call became",
          unit: "bookings",
          buckets: [
            { id: "ok", label: "Successful call", countKey: "feed.outcomes.successfulCall" },
            { id: "noshow", label: "No-show", countKey: "feed.outcomes.noShow", accent: "warn-when-positive" },
            { id: "broke", label: "Call broke", countKey: "feed.outcomes.callBroke", accent: "warn-when-positive" },
            { id: "human", label: "Asked for a human", countKey: "feed.outcomes.askedForHuman" },
            { id: "undetermined", label: "Not determined yet", countKey: "feed.outcomes.undetermined" },
            { id: "notours", label: "Not ours (staff, reschedules)", countKey: "feed.outcomes.notOurs" },
          ],
        },
        { id: "fit", label: "Follow-up sent", countKey: "feed.funnel.followupsSent" },
        {
          // The old vague "In review" pool is gone (same ruling): one amber
          // tile per hold reason, labeled by the feed's own frozen labels
          // map (raw token fallback), capped at 6 plus an Other rollup.
          id: "held", label: "Waiting on David", poolKey: "feed.parkedByReason",
          labelsKey: "feed.labels", tileAccent: "warn-when-positive", unit: "bookings",
        },
      ],
      edges: [
        ["applicants", "invited"], ["invited", "emailed"],
        ["emailed", "booked"], ["booked", "outcome"],
        ["outcome", "fit"], ["outcome", "held"],
      ],
      sourceNote: "Counts from the lane's own published status feed. Outcome and parked counts are per booking (a person can book twice). No-shows and broken calls are only counted here — rebooking them belongs to the lifecycle no-show lane.",
    },
    links: { health: HEALTH, emails: EMAILS, registry: null },
    davidAction: null,
    // "applicants-freshener" and "lane-interview-invites" are RETIRED names
    // from the pre-cutover applicant flow, not live aliases of this lane —
    // kept here only so the completeness test still finds an owner for
    // whatever inventory entries still carry them; do not read them as
    // signal for this row. The live successor is "applicant-pipeline-core".
    dupes: ["interview-fit", "interview-index", "applicants-freshener", "lane-interview-invites"],
  },
  {
    id: "paraform-sequence-email",
    name: "Paraform sequence emails",
    summary: "Follow-up emails Paraform sends for us after calls — no-matches, curated-list follow-ups, and the applicant ladder.",
    group: "candidate-emails",
    priority: 1,
    state: "sending",
    cadence: "Enrollment hourly at :35 (caps 25/run, 100/day) plus a daily 16:00 UTC applicant-ladder drain; Paraform does the sending.",
    gmail: { class: "none", note: "Paraform-delivered as David's connected account" },
    paraform: { class: "writes", note: "enrollments" },
    healthIds: ["gha-paraai-curate", "gha-curate-deadman", "email-paraform-sequences"],
    workflow: "paraai-curate.yml",
    feed: "paraai-curated-fit-heartbeat",
    flow: {
      stages: [
        { id: "discovered", label: "Discovered calls", countKey: "derived.records.discovered" },
        { id: "done", label: "Routed", countKey: "derived.records.done" },
        { id: "skipped", label: "Skipped", countKey: "derived.records.skipped" },
        { id: "failed", label: "Failed", countKey: "derived.records.failed", accent: "bad-when-positive" },
        { id: "pending", label: "Awaiting Talent Network", countKey: "derived.records.pending_tn" },
        { id: "tn", label: "TN registry", countKey: "derived.tnTotal", histogramKey: "derived.tn" },
      ],
      edges: [
        ["discovered", "done"], ["discovered", "skipped"],
        ["discovered", "failed"], ["discovered", "pending"], ["pending", "tn"],
      ],
      sourceNote: "Counts from the lane's public heartbeat.",
    },
    links: { health: HEALTH, emails: EMAILS, registry: null },
    davidAction: null,
    dupes: ["agent-no-matches", "human-no-matches", "agent-curated", "human-curated", "curated-fit-routing", "applicant-ladder", "retired-new-matches"],
  },
  {
    id: "human-handoff",
    name: "Human handoff intro emails",
    summary: "When a screener candidate asks for a human, David gets an email so a person can take over.",
    group: "candidate-emails",
    priority: 2,
    state: "sending",
    cadence: "Every 5 minutes (:01 past), around the clock.",
    gmail: { class: "sends", note: "as david@; ~9/day peak" },
    paraform: { class: "none" },
    healthIds: ["email-human-handoff", "lifecycle-human-handoff"],
    workflow: null,
    feed: null,
    links: { health: HEALTH, emails: EMAILS, registry: "/products/human-handoff/" },
    davidAction: null,
    dupes: ["screener-opt-out"],
  },
  {
    id: "connector-chase",
    name: "Connector referral follow-ups",
    summary: "Chases people who were referred by a connector until they book or say no.",
    group: "candidate-emails",
    priority: 2,
    state: "sending",
    stateNote: "The cold-population sibling (connector-backfill) was retired 2026-08-18 — its backlog drained.",
    cadence: "Every 5 minutes (:02 past), weekdays 9am-6pm PT.",
    gmail: { class: "sends", note: "~140/day steady, peak 147" },
    paraform: { class: "none" },
    healthIds: ["email-connector-chase", "lifecycle-connector-chase"],
    workflow: null,
    feed: null,
    links: { health: HEALTH, emails: EMAILS, registry: null },
    davidAction: null,
    dupes: ["connector-ongoing", "connector-backfill"],
  },
  {
    id: "precall-reminder",
    name: "Pre-call reminders",
    summary: "Reminds a booked candidate one hour before their call.",
    group: "candidate-emails",
    priority: 2,
    state: "sending",
    cadence: "Every 5 minutes; cap 25 per run, 100 a day.",
    gmail: { class: "sends" },
    paraform: { class: "none" },
    healthIds: ["email-precall-reminders"],
    workflow: null,
    feed: null,
    links: { health: HEALTH, emails: EMAILS, registry: null },
    davidAction: null,
    dupes: [],
  },
  {
    id: "scheduler-emails",
    name: "Booking confirmation emails",
    summary: "Everything the booking system emails a candidate about their appointment — confirmations, cancellations, reschedules.",
    group: "candidate-emails",
    priority: 2,
    state: "sending",
    cadence: "Outbox drained every 2 minutes.",
    gmail: { class: "sends", note: "as calls@raydar.xyz — a separate bucket (~233/day)" },
    paraform: { class: "none" },
    healthIds: ["email-scheduler-sender", "booking-door"],
    workflow: null,
    feed: null,
    links: { health: HEALTH, emails: EMAILS, registry: null },
    davidAction: null,
    dupes: ["booking-confirm", "legacy-booking-confirm", "booking-cancel", "booking-reschedule", "calendar-invites"],
  },
  {
    id: "apps-script-auto-reply",
    name: "Paraform candidate auto-reply",
    summary: "Auto-answers candidates who reply to Paraform referral emails, welcoming them on-thread.",
    group: "candidate-emails",
    priority: 2,
    state: "sending",
    cadence: "Every 30 minutes inside David's Google account (reinstalls itself at 10 minutes after any live activation).",
    gmail: { class: "both", note: "runs as David; cap 20/run" },
    paraform: { class: "none" },
    healthIds: ["lane-apps-script-auto-reply"],
    workflow: null,
    feed: null,
    links: { health: HEALTH, emails: EMAILS, registry: null },
    davidAction: {
      id: "apps-script-ping",
      label: "Add the health ping to the Apps Script auto-reply (runs in your Google account)",
      when: "health-row-paused",
    },
    dupes: ["apps-script-reply"],
  },
  {
    id: "lifecycle-followups",
    name: "No-show and audio-failure follow-ups",
    summary: "Candidates whose call never happened or broke get a rebooking email via a Paraform sequence.",
    group: "candidate-emails",
    priority: 2,
    state: "sending",
    cadence: "Cycles at :03/:33 (no-show drain :15/:45, attendance backfill :07/:37); Paraform sends.",
    gmail: { class: "none" },
    paraform: { class: "writes", note: "enrollment; cap 10 confirmations/cycle" },
    healthIds: ["lifecycle-reminders"],
    workflow: null,
    feed: null,
    links: { health: HEALTH, emails: EMAILS, registry: null },
    davidAction: null,
    dupes: ["no-show-followup", "audio-fail-followup"],
  },
  {
    id: "cold-sourcing",
    name: "Cold outreach fleet",
    summary: "First-touch outreach to sourced candidates from 26 separate sending addresses.",
    group: "candidate-emails",
    priority: 2,
    state: "sending",
    cadence: "Weekdays 9am-6pm PT, 3-step ladder, capped 20 per inbox per day.",
    gmail: { class: "none", note: "its own aliases, not david@" },
    paraform: { class: "writes", note: "enrollment via the Sourcing Agent, human-gated" },
    healthIds: ["email-paraform-mailboxes"],
    workflow: null,
    feed: null,
    links: { health: HEALTH, emails: EMAILS, registry: null },
    davidAction: null,
    dupes: [],
  },
  {
    id: "curated-interest-confirm",
    name: "Curated-list interest confirmations",
    summary: "When a candidate says they're interested in a role, they'd get a confirmation email — not turned on yet.",
    group: "candidate-emails",
    priority: 2,
    state: "not-yet",
    stateNote: "Canary routes the next real event to David only; candidate sends need the submission handoff armed — David's call.",
    cadence: "Sweep every 15 minutes once armed; nothing sends today.",
    gmail: { class: "sends", note: "only once armed" },
    paraform: { class: "writes", note: "interest → submission, only once armed" },
    healthIds: [],
    gap: "No health signal — healthId is null in the lane inventory.",
    workflow: null,
    feed: null,
    links: { health: null, emails: EMAILS, registry: "/products/paraai-curated-interest/" },
    davidAction: {
      id: "arm-curated-interest",
      label: "Decide: arm curated-interest candidate emails",
      when: "while-not-yet",
    },
    dupes: ["curated-interest"],
  },
  {
    id: "slack-prefilled",
    name: "Prefilled candidate emails from Slack",
    summary: "Slack offers David a ready-written email; nothing sends unless he clicks.",
    group: "candidate-emails",
    priority: 2,
    state: "manual",
    cadence: "Alerts every 10 minutes (:05), 6am-9pm PT weekdays; sending happens only in David's browser.",
    gmail: { class: "sends", note: "manual, from David's own hand" },
    paraform: { class: "reads", note: "the notify feed" },
    healthIds: ["n8n-workflows"],
    workflow: null,
    feed: null,
    links: { health: HEALTH, emails: EMAILS, registry: "/products/paraform-notify/" },
    davidAction: null,
    dupes: [],
  },
  {
    id: "calendly-role-chat",
    name: "Calendly Role Chat invites",
    summary: "Keeps Alzen's Role Chat calendar invites correct; Google emails the update.",
    group: "candidate-emails",
    priority: 2,
    state: "sending",
    cadence: "Calendar polled every minute; Google sends the invite update.",
    gmail: { class: "none", note: "Google-sent, no quota" },
    paraform: { class: "none" },
    healthIds: ["n8n-workflows"],
    workflow: null,
    feed: null,
    links: { health: HEALTH, emails: EMAILS, registry: "/products/calendly-alzen-bookings/" },
    davidAction: null,
    dupes: [],
  },
  {
    id: "hm-chase",
    name: "Hiring-manager update chase",
    summary: "Chased hiring managers for candidate status updates — retired after clients found the cadence annoying.",
    group: "candidate-emails",
    priority: 2,
    state: "paused",
    stateNote: "Retired 2026-08-08; a restart needs David's explicit go plus a cadence redesign.",
    cadence: "None while paused.",
    gmail: { class: "sends", note: "when it ran, as david@" },
    paraform: { class: "none" },
    healthIds: ["lane-hm-chase"],
    workflow: null,
    feed: null,
    links: { health: HEALTH, emails: EMAILS, registry: null },
    davidAction: null,
    dupes: [],
  },
  {
    id: "resume-chase",
    name: "Para AI resume chase",
    summary: "Chased candidates for a missing resume — retired because resumes are now mandatory at booking.",
    group: "candidate-emails",
    priority: 2,
    state: "paused",
    stateNote: "Retired 2026-08-18.",
    cadence: "None while paused.",
    gmail: { class: "sends", note: "when it ran" },
    paraform: { class: "none" },
    healthIds: ["lane-resume-chase"],
    workflow: null,
    feed: null,
    links: { health: HEALTH, emails: EMAILS, registry: null },
    davidAction: null,
    dupes: [],
  },
  {
    id: "olivia",
    name: "Olivia agent email",
    summary: "The Olivia agent's own email lane — abandoned with zero emails ever sent.",
    group: "candidate-emails",
    priority: 2,
    state: "paused",
    stateNote: "Abandoned 2026-08-18.",
    cadence: "None.",
    gmail: { class: "none", note: "never sent anything" },
    paraform: { class: "none" },
    healthIds: [],
    gap: "Never wired to health; nothing to watch.",
    workflow: null,
    feed: null,
    links: { health: null, emails: EMAILS, registry: null },
    davidAction: null,
    dupes: [],
  },
  {
    // Status v2 build plan step 3 (docs/PRD-STATUS-V2-2026-09-03.md §5.2,
    // §7): the v3 Postgres rebuild of the LinkedIn applicant flow, replacing
    // the old resident Mac worker and its freshener sweep. Registered here
    // so the health surfaces stop implying the retired pre-cutover names
    // below are the live signal for this work — see their `dupes` note.
    // No flow yet: the aggregator has no publisher to draw one from until
    // Core's monitor-live adapter starts sending `pipeline` on sync.
    id: "applicant-pipeline-core",
    name: "Applicant Pipeline Core",
    summary: "Reads LinkedIn applicants, scores fit, and (once armed) invites them to book an AI interview — the v3 Postgres rebuild of the applicant flow.",
    group: "candidate-emails",
    priority: 2,
    state: "not-yet",
    stateNote: "The invite lane is disabled — Core reads and scores applicants but does not send email yet.",
    cadence: "StartInterval desktop job on David's Mac; does not fire while it sleeps.",
    gmail: { class: "none", note: "invites not yet armed" },
    paraform: { class: "writes", note: "applicant records and eligibility" },
    healthIds: [],
    gap: "No publisher yet — Core does not send a heartbeat or a pipeline snapshot to the Monitor today (Status v2 build plan step 3 wires this).",
    workflow: null,
    feed: null,
    links: { health: null, emails: EMAILS, registry: "/products/applicant-hub/" },
    davidAction: null,
    dupes: [],
  },

  // ────────────────────────────────────────────────────────────────────────
  // GROUP 2 — PARAFORM WRITES (no candidate email; they change Paraform state)
  // ────────────────────────────────────────────────────────────────────────
  {
    id: "tn-reenable",
    name: "Talent Network re-enable",
    summary: "Puts candidates we've spoken to in the last 6 months back in front of hiring managers after Paraform's 40-day clock drops them.",
    group: "paraform-writes",
    priority: 3,
    state: "read-only",
    stateNote: "Writes to Paraform, sends no email; kill switch TN_REENABLE_HALT=1. First in line to move to GitHub Actions.",
    cadence: "Daily, 9:20am local, from the desktop.",
    gmail: { class: "reads", note: "holds a cannot-send scope" },
    paraform: { class: "both", note: "agency book + 5 recruiter call feeds (~6,550 meetings/tick); ~11 re-enables/day under the call gate, was ~85" },
    healthIds: ["lane-tn-reenable"],
    workflow: null,
    feed: null,
    flow: {
      // This row's numbers are deliberately the STANDING-PILE clock (current
      // latest status per person) — that is its honest window. Resolved via
      // derived.* so the feed's pile/skipHistogram rename cannot dash it.
      stages: [
        { id: "spoken", label: "Spoken to", countKey: "derived.spokenTo" },
        { id: "intn", label: "In Talent Network", countKey: "derived.inTalentNetwork" },
        { id: "missing", label: "Missing from the network", countKey: "derived.notInNetwork", accent: "warn-when-positive" },
        { id: "offmarket", label: "Off-market, awaiting re-enable", countKey: "derived.offMarket" },
      ],
      edges: [["spoken", "intn"], ["spoken", "missing"], ["intn", "offmarket"]],
      sourceNote: "180-day called cohort, from the match-watch sweep's standing pile (current status per person, not one morning's tick).",
    },
    links: { health: HEALTH, emails: EMAILS, registry: "/products/talent-network-reenable/" },
    davidAction: null,
    dupes: [],
  },
  {
    id: "tn-coverage",
    name: "Talent Network coverage sweep",
    summary: "Daily check that nobody we actually talked to is missing from the Talent Network; builds resumes and submits the missing.",
    group: "paraform-writes",
    priority: 3,
    state: "read-only",
    stateNote: "Writes to Paraform (armed); sends no email. Its run summary is the home of the not-in-TN backlog number.",
    cadence: "Daily, 12:20 UTC (5:20am PT), serialized with the curate tick.",
    unverified: [
      "the widely-quoted 427 not-in-TN figure is unverified on origin/main — pull the live number from the latest tn-coverage run summary",
    ],
    gmail: { class: "none" },
    paraform: { class: "both" },
    healthIds: [],
    gap: "No health-catalog beat row — the run summary is the only signal.",
    workflow: "tn-coverage.yml",
    feed: null,
    links: { health: null, emails: null, registry: null },
    davidAction: null,
    dupes: [],
  },
  {
    id: "paraai-matchmaker",
    name: "Screener-to-Talent-Network submission",
    summary: "A candidate who passes the AI screen is automatically submitted to the Talent Network.",
    group: "paraform-writes",
    priority: 3,
    state: "read-only",
    stateNote: "Beta; sends no email.",
    cadence: "Every 5 minutes with the Para AI worker.",
    gmail: { class: "none" },
    paraform: { class: "both" },
    healthIds: ["paraai-lane", "fly-paraai-worker"],
    workflow: null,
    feed: null,
    links: { health: HEALTH, emails: null, registry: "/products/paraai-matchmaker/" },
    davidAction: null,
    dupes: [],
  },
  {
    id: "referral-auto-accept",
    name: "Referral auto-accept",
    summary: "Accepts strong-tier incoming referrals automatically; leaves weak or unknown ones for a human.",
    group: "paraform-writes",
    priority: 3,
    state: "read-only",
    stateNote: "Watched indirectly through the lifecycle tile — no tile of its own.",
    cadence: "Rides the lifecycle cycle every 30 minutes.",
    gmail: { class: "none" },
    paraform: { class: "writes" },
    healthIds: ["lifecycle-reminders"],
    workflow: null,
    feed: null,
    links: { health: HEALTH, emails: null, registry: "/products/referral-auto-accept/" },
    davidAction: null,
    dupes: [],
  },
  {
    id: "human-outcomes",
    name: "Human-call auto-confirm",
    summary: "Confirms the outcome of human intro calls so downstream lanes know who was actually spoken to.",
    group: "paraform-writes",
    priority: 3,
    state: "read-only",
    cadence: "Every 3 hours at :15.",
    gmail: { class: "none" },
    paraform: { class: "both", note: "outcomes" },
    healthIds: ["gha-human-outcomes"],
    workflow: "human-outcomes.yml",
    feed: null,
    links: { health: HEALTH, emails: null, registry: null },
    davidAction: null,
    dupes: [],
  },
  {
    id: "seq-booking-stop",
    name: "Sequence booking stop",
    summary: "The moment a sequence lead books a call, their email sequence is paused.",
    group: "paraform-writes",
    priority: 3,
    state: "read-only",
    cadence: "Sweeps every 10 minutes (booking sweep :08, membership refresh :01, pause canary :06), plus the Calendly webhook.",
    gmail: { class: "none" },
    paraform: { class: "writes", note: "pauses" },
    healthIds: ["seq-guardian"],
    workflow: null,
    feed: null,
    links: { health: HEALTH, emails: null, registry: "/products/sequence-pause-guardian/" },
    davidAction: null,
    dupes: [],
  },
  {
    id: "protected-recruiter-guard",
    name: "Kyra-protection guardian",
    summary: "Makes sure protected recruiters' candidates are never enrolled or emailed.",
    group: "paraform-writes",
    priority: 3,
    state: "read-only",
    cadence: "Hourly at :17.",
    gmail: { class: "none" },
    paraform: { class: "reads" },
    healthIds: ["seq-guardian"],
    workflow: null,
    feed: null,
    links: { health: HEALTH, emails: null, registry: null },
    davidAction: null,
    dupes: [],
  },
  {
    id: "boost-rotation",
    name: "Super Boost rotation",
    summary: "Ranks who should get our 20 monthly Paraform boosts.",
    group: "paraform-writes",
    priority: 3,
    state: "not-yet",
    stateNote: "Spending is off (ranker only) until David arms it.",
    cadence: "Ranking only until armed.",
    gmail: { class: "none" },
    paraform: { class: "reads" },
    healthIds: [],
    gap: "No health signal.",
    workflow: null,
    feed: null,
    links: { health: null, emails: null, registry: "/products/boost-rotation/" },
    davidAction: {
      id: "arm-boost-rotation",
      label: "Decide: arm boost-rotation spending",
      when: "while-not-yet",
    },
    dupes: [],
  },
  {
    id: "manual-tools",
    name: "Manual tools: Enrich, Sourcing, Sequences",
    summary: "Dashboard tabs where a human finds missing emails, sources candidates into roles, and enrolls CSVs into sequences — nothing runs on its own.",
    group: "paraform-writes",
    priority: 3,
    state: "manual",
    cadence: "Only when a human clicks; every write is confirmation-gated.",
    gmail: { class: "none" },
    paraform: { class: "both", note: "reads + writes, on click" },
    healthIds: ["enrich-health", "inbox-health"],
    workflow: null,
    feed: null,
    links: { health: HEALTH, emails: null, registry: null },
    davidAction: null,
    dupes: ["enrich", "sourcing-agent", "sequences-launcher"],
  },
  {
    id: "candidate-updates",
    name: "Candidate stage updates",
    summary: "Turns Paraform stage changes and comments into Slack pings and Paraform tasks.",
    group: "paraform-writes",
    priority: 3,
    state: "read-only",
    cadence: "Hourly n8n poll.",
    gmail: { class: "none" },
    paraform: { class: "both", note: "reads changes, writes tasks" },
    healthIds: ["n8n-workflows"],
    workflow: null,
    feed: null,
    links: { health: HEALTH, emails: null, registry: null },
    davidAction: null,
    dupes: [],
  },

  // ────────────────────────────────────────────────────────────────────────
  // GROUP 3 — BACKGROUND READERS (they spend Gmail quota or poll Paraform;
  // send nothing)
  // ────────────────────────────────────────────────────────────────────────
  {
    id: "booking-resume-family",
    name: "Booking resume sync",
    summary: "Attaches the resume from each booking to the right Paraform profile.",
    group: "background-readers",
    priority: 4,
    state: "read-only",
    stateNote: "Pinned to macOS by the resume-parser sandbox; cloud-Mac move on hold.",
    cadence: "Sync every 5 minutes (:03), retry every 15 (:06), email-index daily.",
    unverified: [
      "email-index daily time: lanes.mjs says 04:00 UTC, the migration PRD says 04:20 — resolve from the plist",
    ],
    gmail: { class: "reads", note: "the historical #1 reader (~992k units/day before caching)" },
    paraform: { class: "writes", note: "resume attach" },
    healthIds: ["lane-booking-resume-sync", "lane-booking-resume-retry", "lane-booking-resume-email-index"],
    workflow: null,
    feed: null,
    links: { health: HEALTH, emails: EMAILS, registry: null },
    davidAction: null,
    dupes: ["booking-resume-sync", "booking-resume-retry", "booking-email-index"],
  },
  {
    id: "resume-feed",
    name: "Resume mailbox ingest",
    summary: "Reads the resume@metawork.us mailbox and files each resume into Paraform, with a historical backfill alongside.",
    group: "background-readers",
    priority: 4,
    state: "read-only",
    stateNote: "A separate mailbox and credential — proof that bucket-splitting works.",
    cadence: "Feed every 15 minutes; archive backfill every 30 (:05).",
    gmail: { class: "reads", note: "resume@metawork.us — its own bucket, not david@" },
    paraform: { class: "writes", note: "candidate create/attach" },
    healthIds: ["lane-resume-feed", "lane-archive-backfill"],
    workflow: null,
    feed: null,
    links: { health: HEALTH, emails: EMAILS, registry: null },
    davidAction: null,
    dupes: ["archive-backfill"],
  },
  {
    id: "applicant-hub",
    name: "Applicant hub",
    summary: "Keeps LinkedIn and Workable applicant records synchronized into Paraform.",
    group: "background-readers",
    priority: 4,
    state: "read-only",
    stateNote: "11.3 GB of local state; stays on a Mac.",
    cadence: "Resident worker (always on) plus a 10-minute watchdog.",
    gmail: { class: "reads", note: "via ledgers" },
    paraform: { class: "writes" },
    healthIds: ["lane-applicant-hub-worker", "lane-applicant-hub-watchdog"],
    workflow: null,
    feed: null,
    links: { health: HEALTH, emails: EMAILS, registry: null },
    davidAction: null,
    // "applicant-hub-worker" is a RETIRED name — the resident Mac worker this
    // row describes is the pre-cutover applicant flow; the v3 rebuild is the
    // separate "applicant-pipeline-core" row above. Kept here only so the
    // completeness test still finds an owner for lanes.mjs' entry.
    dupes: ["applicant-hub-worker"],
  },
  {
    id: "paraform-notify",
    name: "Paraform notify feed",
    summary: "Watches the Paraform feed and notification mail, and pings Slack with anything new.",
    group: "background-readers",
    priority: 4,
    state: "read-only",
    stateNote: "The send side is the 'Prefilled candidate emails from Slack' row above.",
    cadence: "Every 10 minutes (:05), business hours, plus the Slack action router.",
    gmail: { class: "reads", note: "david@ notification mail" },
    paraform: { class: "reads" },
    healthIds: ["n8n-workflows"],
    workflow: null,
    feed: null,
    links: { health: HEALTH, emails: EMAILS, registry: "/products/paraform-notify/" },
    davidAction: null,
    dupes: ["n8n-paraform-notify"],
  },
  {
    id: "submission-notify",
    name: "Submission response notifications",
    summary: "Slack ping when a candidate responds about a submission.",
    group: "background-readers",
    priority: 4,
    state: "read-only",
    cadence: "Hourly at :20.",
    gmail: { class: "reads" },
    paraform: { class: "reads" },
    healthIds: [],
    gap: "healthId is null in the lane inventory — no tile watches it.",
    workflow: null,
    feed: null,
    links: { health: null, emails: EMAILS, registry: null },
    davidAction: null,
    dupes: [],
  },
  {
    id: "booking-evidence",
    name: "Booking evidence oracle",
    summary: "On-demand Gmail and Calendar lookups that prove whether a booking actually happened — fail-closed, read-only.",
    group: "background-readers",
    priority: 4,
    state: "read-only",
    cadence: "On demand (webhook) — no schedule.",
    gmail: { class: "reads", note: "the no-show gate's oracle; Calendar reads too" },
    paraform: { class: "none" },
    healthIds: ["n8n-workflows"],
    workflow: null,
    feed: null,
    links: { health: HEALTH, emails: EMAILS, registry: null },
    davidAction: null,
    dupes: ["n8n-booking-evidence", "booking-resume-calendar-adapter"],
  },
  {
    id: "paraai-interest-observer",
    name: "Interest observer (shadow)",
    summary: "Watches curated-list interest events in shadow mode without acting on them.",
    group: "background-readers",
    priority: 4,
    state: "read-only",
    cadence: "Every 10 minutes from the desktop; the Actions copy is dispatch-only (dark).",
    unverified: ["its beat lane id is unverified — no catalog row claims it"],
    gmail: { class: "none" },
    paraform: { class: "reads" },
    healthIds: [],
    gap: "Observer beat lane id unverified; no health-catalog row claims it.",
    workflow: null,
    feed: null,
    links: { health: null, emails: null, registry: null },
    davidAction: null,
    dupes: [],
  },
  {
    id: "fyxer",
    name: "Fyxer",
    summary: "David's email-drafting agent reads the mailbox and drafts replies.",
    group: "background-readers",
    priority: 4,
    state: "read-only",
    cadence: "Always on (vendor SaaS).",
    gmail: { class: "both", note: "reads + drafts, largely invisible to monitoring" },
    paraform: { class: "none" },
    healthIds: [],
    gap: "Vendor SaaS with no health signal by design — listed so the mailbox's readers are complete.",
    workflow: null,
    feed: null,
    links: { health: null, emails: EMAILS, registry: null },
    davidAction: null,
    dupes: [],
  },

  // ────────────────────────────────────────────────────────────────────────
  // GROUP 4 — INFRASTRUCTURE (screening, scheduling, monitoring — the rest)
  // ────────────────────────────────────────────────────────────────────────
  {
    id: "screener-dispatch",
    name: "Screener dispatch",
    summary: "The AI screener's dispatch pipeline — calendar polling, reconciliation, backfill, and duplicate eviction.",
    group: "infrastructure",
    priority: 5,
    state: "frozen",
    stateNote: "FROZEN — never modified without David's direct order.",
    cadence: "Calendar poll every minute, reconcile every 10, Fyxer backfill every 15, guardian every minute.",
    gmail: { class: "none" },
    paraform: { class: "reads", note: "reconcile events" },
    healthIds: ["n8n-workflows", "screener-feed"],
    workflow: null,
    feed: null,
    links: { health: HEALTH, emails: null, registry: "/products/screener/" },
    davidAction: null,
    dupes: [],
  },
  {
    id: "audio-bridge",
    name: "Audio bridge",
    summary: "The voice of the AI screener.",
    group: "infrastructure",
    priority: 5,
    state: "read-only",
    cadence: "Resident Fly app — always on.",
    gmail: { class: "none" },
    paraform: { class: "none" },
    healthIds: ["screener-uplink", "fly-bridge"],
    workflow: null,
    feed: null,
    links: { health: HEALTH, emails: null, registry: "/products/screener/" },
    davidAction: null,
    dupes: [],
  },
  {
    id: "webview-monitor-feed",
    name: "Screener monitor feed",
    summary: "The webview crons that keep the live screener board fed and warm.",
    group: "infrastructure",
    priority: 5,
    state: "read-only",
    cadence: "Monitor, warm and names every 3 minutes; canary hourly; rollup daily 9:00.",
    gmail: { class: "none" },
    paraform: { class: "none" },
    healthIds: ["screener-feed"],
    workflow: null,
    feed: null,
    links: { health: HEALTH, emails: null, registry: null },
    davidAction: null,
    dupes: [],
  },
  {
    id: "scheduler-core",
    name: "Scheduler core",
    summary: "book.raydar.xyz — the booking system's worker, sweeps, health probes, and cron guard.",
    group: "infrastructure",
    priority: 5,
    state: "read-only",
    stateNote: "Its candidate emails appear above as 'Booking confirmation emails'.",
    cadence: "Worker every 2 minutes; sweep and health every 5; monitor every 15; cron guard every 5 (GitHub Actions).",
    gmail: { class: "none" },
    paraform: { class: "none" },
    healthIds: ["booking-door", "gha-scheduler-cron-guard"],
    workflow: null,
    feed: null,
    links: { health: HEALTH, emails: null, registry: null },
    davidAction: null,
    dupes: ["scheduler-heartbeat"],
  },
  {
    id: "mailroom",
    name: "Mailroom",
    summary: "Email System v2's shared outbox — delivers mail on behalf of migrated lanes.",
    group: "infrastructure",
    priority: 5,
    state: "sending",
    cadence: "Shared outbox drained every 2 minutes.",
    gmail: { class: "sends", note: "on behalf of migrated lanes" },
    paraform: { class: "none" },
    healthIds: ["email-mailroom"],
    workflow: null,
    feed: null,
    links: { health: HEALTH, emails: EMAILS, registry: null },
    davidAction: null,
    dupes: [],
  },
  {
    id: "calls-api",
    name: "Calls API",
    summary: "Serves every recorded screening call and its durable share links.",
    group: "infrastructure",
    priority: 5,
    state: "read-only",
    cadence: "Request-driven; no crons.",
    gmail: { class: "none" },
    paraform: { class: "none" },
    healthIds: ["calls-api"],
    workflow: null,
    feed: null,
    links: { health: HEALTH, emails: null, registry: null },
    davidAction: null,
    dupes: [],
  },
  {
    id: "prepdoc",
    name: "Prep docs",
    summary: "Builds interview prep PDFs on demand and files them as Gmail drafts.",
    group: "infrastructure",
    priority: 5,
    state: "read-only",
    cadence: "On demand.",
    gmail: { class: "reads", note: "creates prep drafts in the mailbox; never sends" },
    paraform: { class: "none" },
    healthIds: ["fly-prepdoc"],
    workflow: null,
    feed: null,
    links: { health: HEALTH, emails: null, registry: null },
    davidAction: null,
    dupes: [],
  },
  {
    id: "dashboard-plane",
    name: "Dashboard data plane",
    summary: "monitor.raydar.xyz's own crons — the health tick, quota witness, digests, and watchdog relays this very page rides.",
    group: "infrastructure",
    priority: 5,
    state: "read-only",
    cadence: "Health tick every 2 minutes; quota witness every 15; digests daily; watchdog relays every 15.",
    gmail: { class: "reads", note: "one Sent-search per 15 minutes (5 units) — the only Gmail call in the status plane" },
    paraform: { class: "none" },
    healthIds: [],
    gap: "The watcher itself — when it dies, this whole page goes stale (watch the data-as-of stamp).",
    workflow: null,
    feed: null,
    links: { health: HEALTH, emails: null, registry: "/products/monitor/" },
    davidAction: null,
    dupes: [],
  },
  {
    id: "gha-watchdogs",
    name: "GitHub Actions watchdogs",
    summary: "The backstops that watch the watchers — cron and health backstops, the lifecycle watchdog, snapshots, and the trademark watch.",
    group: "infrastructure",
    priority: 5,
    state: "read-only",
    stateNote: "trademark-watch mails David its digest — the only GHA sender outside match-watch.",
    cadence: "Backstops hourly (:20/:23); lifecycle watchdog every 15 minutes; daily sentinels through the day.",
    unverified: ["repo-health-sentinel has no beat row — its runs are invisible to Health"],
    gmail: { class: "sends", note: "2 trademark-watch digest emails to David — nothing candidate-facing" },
    paraform: { class: "none" },
    healthIds: ["gha-cron-backstop", "gha-health-backstop", "gha-lifecycle-watchdog", "gha-trademark-watch", "gha-clients-snapshot"],
    workflow: null,
    feed: null,
    links: { health: HEALTH, emails: EMAILS, registry: null },
    davidAction: null,
    dupes: ["trademark-watch", "repo-health-sentinel"],
  },
  {
    id: "desktop-support",
    name: "Desktop support jobs",
    summary: "The Mac's own housekeeping — the health reporter, snapshots, resume watchdogs and backups, plus the deliberately-unloaded spares.",
    group: "infrastructure",
    priority: 5,
    state: "read-only",
    stateNote: "resume-forward-v2 and resume-migration-v2 are unloaded on purpose (paused rows).",
    cadence: "Reporter every 5 minutes; snapshot and backups daily; watchdogs resident.",
    gmail: { class: "none" },
    paraform: { class: "none" },
    healthIds: [
      "desktop-runner",
      "lane-resume-watchdog-v2",
      "lane-resume-ledger-backup-v2",
      "lane-resume-juicebox-bridge-v1",
      "lane-resume-forward-v2",
      "lane-resume-migration-v2",
      "lane-cohort-booking-watch",
      "lane-interview-sheet-mirror",
    ],
    workflow: null,
    feed: null,
    links: { health: HEALTH, emails: null, registry: null },
    davidAction: null,
    dupes: ["health-reporter", "desktop-snapshot", "resume-watchdog-v2", "resume-ledger-backup-v2", "resume-juicebox-bridge-v1"],
  },
  {
    id: "claude-scheduled-tasks",
    name: "Claude scheduled tasks",
    summary: "Eight scheduled Claude agent sessions on David's desktop — interview sheet, no-bot guardian, reschedule detector, interest shadow report, corpus reviews, boost assignment, and screener-script verification.",
    group: "infrastructure",
    priority: 5,
    state: "read-only",
    stateNote: "raydar-reschedule-detector was flagged 'needs checking' on 2026-08-20.",
    cadence: "Per-task schedules; cadences unverified (desktop-only store).",
    unverified: ["cadences unverifiable read-only — the schedule store lives only on the desktop"],
    gmail: { class: "none" },
    paraform: { class: "none" },
    healthIds: [],
    gap: "No health signal for any scheduled agent session.",
    workflow: null,
    feed: null,
    links: { health: null, emails: null, registry: null },
    davidAction: null,
    dupes: [],
  },
  {
    id: "deps",
    name: "Shared dependencies",
    summary: "The services everything else leans on — the Paraform login cookie, Google Workspace, the databases, n8n, Slack, and the call vendors.",
    group: "infrastructure",
    priority: 5,
    state: "read-only",
    cadence: "Checked every 2 minutes by the health tick.",
    gmail: { class: "none" },
    paraform: { class: "none" },
    healthIds: [
      "paraform-session",
      "google-workspace",
      "neon-db",
      "upstash-kv",
      "n8n-cloud",
      "slack-transport",
      "recall-api",
      "vapi-api",
      "email-inbox-david",
    ],
    workflow: null,
    feed: null,
    links: { health: HEALTH, emails: EMAILS, registry: null },
    davidAction: {
      id: "paraform-cookie",
      label: "Log into Paraform in Chrome so the session can be recaptured",
      when: "tile-paraform-session-down",
    },
    dupes: [],
  },
];

export const systemsById = new Map(SYSTEMS.map((s) => [s.id, s]));
