import { createHash } from "node:crypto";
import { lstat, mkdir, readFile, readdir, rename, writeFile } from "node:fs/promises";
import { dirname, relative, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";

const SCRIPT_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const MANIFEST_JSON = "submissions-v2-release.json";
const MANIFEST_MODULE = "api/submissions-v2/_lib/release-manifest.mjs";
const FIXED_FILES = Object.freeze([
  "package.json",
  "package-lock.json",
  "submissions-v2.html",
  "submissions-v2.css",
  "submissions-v2.js",
  "submissions-v2-ui-state.mjs",
  "api/submissions-v2-dispatch.mjs",
  "api/inbox/_lib/core.mjs",
  "api/inbox/health.mjs",
  "api/seq/_lib/core.mjs",
  "api/seq/_lib/scheduling-links.mjs",
  "api/sourcing/_lib/store.mjs",
  "api/roster/_lib/outcome-sequences.mjs",
  "api/paraai/_lib/core.mjs",
  "api/auth/_lib/session.mjs",
  "scripts/migrate-submissions-v2.mjs",
  "scripts/submissions-release.mjs",
  ".vercelignore",
  "vercel.json",
]);
const FIXED_DIRECTORIES = Object.freeze([
  ["api/submissions-v2", (path) => path.endsWith(".mjs") && path !== MANIFEST_MODULE],
  ["submissions-v2-worker", (path) => /(?:\.mjs|\/Dockerfile|\/fly\.toml)$/u.test(path)],
  ["resume-renderer-v2", (path) => /(?:\.mjs|\.py|\.svg|\.txt|\/Dockerfile|\/fly\.toml)$/u.test(path) && !/(?:^|\/)test[^/]*\.(?:mjs|py)$/u.test(path)],
  ["migrations/submissions-v2", (path) => path.endsWith(".sql")],
]);

const sha256 = (value) => createHash("sha256").update(value).digest("hex");
const normalize = (value) => value.split(sep).join("/");
const isForbidden = (path) => path.split("/").some((part) => part === ".env" || part.startsWith(".env."));
const deploymentOmitted = (path) => path === "scripts/migrate-submissions-v2.mjs"
  || path.startsWith("migrations/submissions-v2/")
  || path.startsWith("resume-renderer-v2/")
  || path.startsWith("submissions-v2-purge/")
  || path.startsWith("submissions-v2-worker/");

function canonicalJson(value) {
  if (Array.isArray(value)) return `[${value.map(canonicalJson).join(",")}]`;
  if (value && typeof value === "object") {
    return `{${Object.keys(value).sort().map((key) => `${JSON.stringify(key)}:${canonicalJson(value[key])}`).join(",")}}`;
  }
  return JSON.stringify(value);
}

async function vercelJsonCanonicalSha256(root) {
  let config;
  try { config = JSON.parse(await readFile(resolve(root, "vercel.json"), "utf8")); }
  catch { throw new Error("Submissions release manifest requires valid vercel.json"); }
  return sha256(canonicalJson(config));
}

async function walk(root, directory, accepts) {
  const absolute = resolve(root, directory);
  const entries = await readdir(absolute, { withFileTypes: true });
  const paths = [];
  for (const entry of entries.sort((left, right) => left.name.localeCompare(right.name))) {
    const child = normalize(relative(root, resolve(absolute, entry.name)));
    if (entry.isDirectory()) paths.push(...await walk(root, child, accepts));
    else if (entry.isSymbolicLink()) throw new Error(`Release manifest does not accept symlinks: ${child}`);
    else if (entry.isFile() && accepts(child) && !isForbidden(child)) paths.push(child);
  }
  return paths;
}

async function fileEntry(root, path) {
  const absolute = resolve(root, path);
  const stats = await lstat(absolute);
  if (!stats.isFile() || stats.isSymbolicLink()) throw new Error(`Release manifest requires a regular file: ${path}`);
  return { path, sha256: sha256(await readFile(absolute)) };
}

export async function buildSubmissionsReleaseManifest({ root = SCRIPT_ROOT } = {}) {
  const resolvedRoot = resolve(root);
  const paths = [...FIXED_FILES];
  for (const [directory, accepts] of FIXED_DIRECTORIES) paths.push(...await walk(resolvedRoot, directory, accepts));
  const files = await Promise.all([...new Set(paths)].sort().map((path) => fileEntry(resolvedRoot, path)));
  const digest = sha256(files.map((file) => `${file.path}\0${file.sha256}\n`).join(""));
  return {
    schema_version: 2,
    algorithm: "sha256",
    file_count: files.length,
    digest,
    vercel_json_canonical_sha256: await vercelJsonCanonicalSha256(resolvedRoot),
    files,
  };
}

async function buildDeploymentReleaseFiles({ root = SCRIPT_ROOT } = {}) {
  const resolvedRoot = resolve(root);
  const paths = FIXED_FILES.filter((path) => !deploymentOmitted(path));
  for (const [directory, accepts] of FIXED_DIRECTORIES) {
    if (!deploymentOmitted(`${directory}/`)) paths.push(...await walk(resolvedRoot, directory, accepts));
  }
  return Promise.all([...new Set(paths)].sort().map((path) => fileEntry(resolvedRoot, path)));
}

function manifestModule(manifest) {
  return `// Generated by scripts/submissions-release.mjs --write. Do not edit.\nexport const SUBMISSIONS_V2_RELEASE_MANIFEST = Object.freeze(${JSON.stringify(manifest, null, 2)});\n\nexport function submissionsV2ReleaseManifest() { return SUBMISSIONS_V2_RELEASE_MANIFEST; }\n`;
}

async function atomicWrite(path, body) {
  await mkdir(dirname(path), { recursive: true });
  const temporary = `${path}.tmp-${process.pid}`;
  await writeFile(temporary, body);
  await rename(temporary, path);
}

export async function writeSubmissionsReleaseManifest({ root = SCRIPT_ROOT } = {}) {
  const resolvedRoot = resolve(root);
  const manifest = await buildSubmissionsReleaseManifest({ root: resolvedRoot });
  await atomicWrite(resolve(resolvedRoot, MANIFEST_JSON), `${JSON.stringify(manifest, null, 2)}\n`);
  await atomicWrite(resolve(resolvedRoot, MANIFEST_MODULE), manifestModule(manifest));
  return manifest;
}

function equalManifest(expected, actual) {
  return JSON.stringify(expected) === JSON.stringify(actual);
}

export async function checkSubmissionsReleaseManifest({ root = SCRIPT_ROOT } = {}) {
  const resolvedRoot = resolve(root);
  let expected;
  try { expected = JSON.parse(await readFile(resolve(resolvedRoot, MANIFEST_JSON), "utf8")); }
  catch { throw new Error(`Submissions release manifest is missing or invalid; run node scripts/submissions-release.mjs --write`); }
  const actual = await buildSubmissionsReleaseManifest({ root: resolvedRoot });
  if (!equalManifest(expected, actual)) throw new Error(`Submissions release manifest is stale; run node scripts/submissions-release.mjs --write`);
  let generated;
  try { generated = await readFile(resolve(resolvedRoot, MANIFEST_MODULE), "utf8"); }
  catch { throw new Error(`Submissions release manifest module is missing; run node scripts/submissions-release.mjs --write`); }
  if (generated !== manifestModule(actual)) throw new Error(`Submissions release manifest module is stale; run node scripts/submissions-release.mjs --write`);
  return actual;
}

/** Checks the reduced Vercel build context against the full committed manifest. */
export async function checkSubmissionsReleaseDeploymentManifest({ root = SCRIPT_ROOT } = {}) {
  const resolvedRoot = resolve(root);
  let expected;
  try { expected = JSON.parse(await readFile(resolve(resolvedRoot, MANIFEST_JSON), "utf8")); }
  catch { throw new Error(`Submissions release manifest is missing or invalid; run node scripts/submissions-release.mjs --write`); }
  let generated;
  try { generated = await readFile(resolve(resolvedRoot, MANIFEST_MODULE), "utf8"); }
  catch { throw new Error(`Submissions release manifest module is missing; run node scripts/submissions-release.mjs --write`); }
  if (generated !== manifestModule(expected)) throw new Error(`Submissions release manifest module is stale; run node scripts/submissions-release.mjs --write`);
  if (typeof expected.vercel_json_canonical_sha256 !== "string") {
    throw new Error("Submissions release manifest is missing the Vercel config digest; run node scripts/submissions-release.mjs --write");
  }
  const actualFiles = await buildDeploymentReleaseFiles({ root: resolvedRoot });
  const expectedByPath = new Map((expected.files || []).map((file) => [file.path, file.sha256]));
  for (const file of actualFiles) {
    if (file.path === "vercel.json") continue;
    if (expectedByPath.get(file.path) !== file.sha256) throw new Error(`Submissions deployment release manifest is stale: ${file.path}`);
  }
  if (await vercelJsonCanonicalSha256(resolvedRoot) !== expected.vercel_json_canonical_sha256) {
    throw new Error("Submissions deployment release manifest is stale: vercel.json");
  }
  const actualPaths = new Set(actualFiles.map((file) => file.path));
  for (const file of expected.files || []) {
    if (!actualPaths.has(file.path) && !deploymentOmitted(file.path)) {
      throw new Error(`Submissions deployment release manifest is missing required file: ${file.path}`);
    }
  }
  return { ...expected, deployed_file_count: actualFiles.length };
}

async function main(argumentsList) {
  const args = new Set(argumentsList);
  const rootIndex = argumentsList.indexOf("--root");
  const root = rootIndex >= 0 ? argumentsList[rootIndex + 1] : SCRIPT_ROOT;
  if (rootIndex >= 0 && !root) throw new Error("--root requires a directory");
  if (args.has("--write") === args.has("--check") || (args.has("--deployment") && !args.has("--check"))) throw new Error("Use --write, --check, or --check --deployment");
  const manifest = args.has("--write")
    ? await writeSubmissionsReleaseManifest({ root })
    : args.has("--deployment")
      ? await checkSubmissionsReleaseDeploymentManifest({ root })
      : await checkSubmissionsReleaseManifest({ root });
  process.stdout.write(`Submissions release manifest ${args.has("--write") ? "sealed" : "matches"}: ${manifest.digest}\n`);
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main(process.argv.slice(2)).catch((error) => {
    process.stderr.write(`${error.message}\n`);
    process.exitCode = 1;
  });
}
